spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gelin?useUnicode=true&characterEncoding=utf-8
    username: gelin
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  resources:
    static-locations: classpath:static/,file:static/
logging:
  level:
    root: warn
    com.glsw: info
  file:
    name: log/gelin-pro.log
server:
  port: 8081
